---
version: "3"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    hostname: vpn.vogoon.dev
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "true"
    tty: true
    networks:
      - dokploy-network
    network_mode: host
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.next-app.rule=Host(`vpn.vogoon.dev`)
      - traefik.http.routers.next-app.entrypoints=websecure
      - traefik.http.routers.next-app.tls.certResolver=letsencrypt
      - traefik.http.services.next-app.loadbalancer.server.port=3000
networks:
  dokploy-network:
    external: true
